<?php

namespace App\Filament\Resources\ConformidadeResource\Custom;



use Closure;
use Filament\Tables\Actions\BulkAction;

class CustomBulkSelect extends BulkAction
{
    public function fetchSelectedRecords(bool|Closure $condition = true): static
    {
        dd('oi');
        return parent::fetchSelectedRecords($condition); // TODO: Change the autogenerated stub
    }
}
